import 'package:flutter/material.dart';

/* Rectangle - - - - - VENDEUR SECTION - - - - -
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVENDEURSECTIONWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 23.0,
      height: 1838.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(50.0),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(50.0),
        child: Container(
          color: Color.fromARGB(255, 196, 104, 204),
        ),
      ),
    ));
  }
}
