import 'package:flutter/material.dart';
import 'package:flutterapp/sutch_clientapp/generatedclientinterfacewidget/generated/GeneratedBKGWidget448.dart';
import 'package:flutterapp/sutch_clientapp/generatedclientinterfacewidget/generated/GeneratedCARDFLIPWidget8.dart';
import 'package:flutterapp/sutch_clientapp/generatedclientinterfacewidget/generated/GeneratedCATEGORIEWidget4.dart';
import 'package:flutterapp/sutch_clientapp/generatedclientinterfacewidget/generated/GeneratedCARDFLIPWidget7.dart';
import 'package:flutterapp/sutch_clientapp/generatedclientinterfacewidget/generated/GeneratedBackgroundWidget25.dart';
import 'package:flutterapp/sutch_clientapp/generatedclientinterfacewidget/generated/GeneratedCARDFLIPWidget5.dart';
import 'package:flutterapp/sutch_clientapp/generatedclientinterfacewidget/generated/GeneratedCARDFLIPWidget1.dart';
import 'package:flutterapp/sutch_clientapp/generatedclientinterfacewidget/generated/GeneratedTOOLBARWidget15.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/sutch_clientapp/generatedclientinterfacewidget/generated/GeneratedCARDFLIPWidget4.dart';
import 'package:flutterapp/sutch_clientapp/generatedclientinterfacewidget/generated/GeneratedTRIEWidget2.dart';
import 'package:flutterapp/sutch_clientapp/generatedclientinterfacewidget/generated/GeneratedCARDFLIPWidget6.dart';
import 'package:flutterapp/sutch_clientapp/generatedclientinterfacewidget/generated/GeneratedCARDFLIPWidget3.dart';
import 'package:flutterapp/sutch_clientapp/generatedclientinterfacewidget/generated/GeneratedHeaderWidget11.dart';
import 'package:flutterapp/sutch_clientapp/generatedclientinterfacewidget/generated/GeneratedCARDFLIPWidget2.dart';

/* Frame                                  CLIENT Interface
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCLIENTInterfaceWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 375.0,
              height: 812.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 244, 244, 244),
                      ),
                    ),
                    Positioned(
                      left: 8.0,
                      top: 812.0,
                      right: null,
                      bottom: null,
                      width: 176.0,
                      height: 258.0,
                      child: GeneratedCARDFLIPWidget1(),
                    ),
                    Positioned(
                      left: 191.0,
                      top: 812.0,
                      right: null,
                      bottom: null,
                      width: 176.0,
                      height: 258.0,
                      child: GeneratedCARDFLIPWidget2(),
                    ),
                    Positioned(
                      left: 8.0,
                      top: 1092.0,
                      right: null,
                      bottom: null,
                      width: 176.0,
                      height: 258.0,
                      child: GeneratedCARDFLIPWidget3(),
                    ),
                    Positioned(
                      left: 191.0,
                      top: 1092.0,
                      right: null,
                      bottom: null,
                      width: 176.0,
                      height: 258.0,
                      child: GeneratedCARDFLIPWidget4(),
                    ),
                    Positioned(
                      left: 8.0,
                      top: 173.0,
                      right: null,
                      bottom: null,
                      width: 176.0,
                      height: 258.0,
                      child: GeneratedCARDFLIPWidget5(),
                    ),
                    Positioned(
                      left: 191.0,
                      top: 173.0,
                      right: null,
                      bottom: null,
                      width: 176.0,
                      height: 258.0,
                      child: GeneratedCARDFLIPWidget6(),
                    ),
                    Positioned(
                      left: 8.0,
                      top: 453.0,
                      right: null,
                      bottom: null,
                      width: 176.0,
                      height: 258.0,
                      child: GeneratedCARDFLIPWidget7(),
                    ),
                    Positioned(
                      left: 191.0,
                      top: 453.0,
                      right: null,
                      bottom: null,
                      width: 176.0,
                      height: 258.0,
                      child: GeneratedCARDFLIPWidget8(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width = constraints.maxWidth * 1.08;

                        final double height =
                            constraints.maxHeight * 0.07881773399014778;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: constraints.maxWidth * -0.04,
                              y: constraints.maxHeight * -0.09113300492610837,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child: GeneratedBackgroundWidget25(),
                              ))
                        ]);
                      }),
                    )
                  ]),
            ),
            Positioned(
              left: 0.0,
              top: -4.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 816.0,
              child: GeneratedBKGWidget448(),
            ),
            Positioned(
              left: 4.0,
              top: 742.0,
              right: null,
              bottom: null,
              width: 367.0,
              height: 44.0,
              child: GeneratedTOOLBARWidget15(),
            ),
            Positioned(
              left: 4.0,
              top: 128.0,
              right: null,
              bottom: null,
              width: 355.0,
              height: 24.0,
              child: GeneratedTRIEWidget2(),
            ),
            Positioned(
              left: 4.0,
              top: 82.0,
              right: null,
              bottom: null,
              width: 343.0,
              height: 35.0,
              child: GeneratedCATEGORIEWidget4(),
            ),
            Positioned(
              left: -155.0,
              top: -35.0,
              right: null,
              bottom: null,
              width: 520.0,
              height: 109.0,
              child: GeneratedHeaderWidget11(),
            )
          ]),
    ));
  }
}
