import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/sutch_clientapp/generatedcatavanceewidget1/generated/GeneratedPolygon1Widget1.dart';
import 'package:flutterapp/sutch_clientapp/generatedcatavanceewidget1/generated/GeneratedHOMMEWidget2.dart';
import 'package:flutterapp/sutch_clientapp/generatedcatavanceewidget1/generated/GeneratedRectangle11Widget10.dart';
import 'package:flutterapp/sutch_clientapp/generatedcatavanceewidget1/generated/GeneratedFEMMEWidget2.dart';

/* Instance CAT AVANCEE
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCATAVANCEEWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 184.0,
      height: 178.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(30.0),
      ),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.circular(30.0),
              child: Container(
                color: Color.fromARGB(255, 244, 244, 244),
              ),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                double percentWidth = 0.11413045551465906;
                double scaleX =
                    (constraints.maxWidth * percentWidth) / 21.000003814697266;

                double percentHeight = 0.11797754952077115;
                double scaleY = (constraints.maxHeight * percentHeight) /
                    21.000003814697266;

                return Stack(children: [
                  TransformHelper.translateAndScale(
                      translateX: constraints.maxWidth * 0.16304347826086957,
                      translateY: constraints.maxHeight * -0.11797752808988764,
                      translateZ: 0,
                      scaleX: scaleX,
                      scaleY: scaleY,
                      scaleZ: 1,
                      child: GeneratedPolygon1Widget1())
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.9619565217391305;

                final double height = constraints.maxHeight;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.021739130434782608,
                      y: constraints.maxHeight * -0.016853932584269662,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedRectangle11Widget10(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.44565217391304346;

                final double height =
                    constraints.maxHeight * 0.9325842696629213;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.5163043478260869,
                      y: constraints.maxHeight * 0.016853932584269662,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedHOMMEWidget2(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.41847826086956524;

                final double height =
                    constraints.maxHeight * 0.9325842696629213;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.043478260869565216,
                      y: constraints.maxHeight * 0.016853932584269662,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedFEMMEWidget2(),
                      ))
                ]);
              }),
            )
          ]),
    ));
  }
}
