import 'package:flutter/material.dart';
import 'package:flutterapp/sutch_clientapp/generatedclienttlbwidget/generated/GeneratedREFRESHWidget2.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/sutch_clientapp/generatedclienttlbwidget/generated/GeneratedClavierWidget2.dart';
import 'package:flutterapp/sutch_clientapp/generatedclienttlbwidget/generated/GeneratedBackgroundWidget5.dart';
import 'package:flutterapp/sutch_clientapp/generatedclienttlbwidget/generated/GeneratedTEANSACTIONWidget1.dart';
import 'package:flutterapp/sutch_clientapp/generatedclienttlbwidget/generated/GeneratedHEADERSWidget1.dart';
import 'package:flutterapp/sutch_clientapp/generatedclienttlbwidget/generated/GeneratedHEADBARWidget2.dart';
import 'package:flutterapp/sutch_clientapp/generatedclienttlbwidget/generated/GeneratedTOOLBARWidget3.dart';
import 'package:flutterapp/sutch_clientapp/generatedclienttlbwidget/generated/GeneratedACTUSWidget2.dart';
import 'package:flutterapp/sutch_clientapp/generatedclienttlbwidget/generated/GeneratedCARDVENDEURWidget2.dart';

/* Frame Client / TLB
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedClientTLBWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 375.0,
              height: 817.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 244, 244, 244),
                      ),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 812.0,
                      right: null,
                      bottom: null,
                      width: 375.0,
                      height: 293.0,
                      child: GeneratedClavierWidget2(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width = constraints.maxWidth * 1.08;

                        final double height =
                            constraints.maxHeight * 0.07881773408215079;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: constraints.maxWidth * -0.04,
                              y: constraints.maxHeight * -0.09113300561613086,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child: GeneratedBackgroundWidget5(),
                              ))
                        ]);
                      }),
                    )
                  ]),
            ),
            Positioned(
              left: 14.0,
              top: 463.0,
              right: null,
              bottom: null,
              width: 348.0,
              height: 266.0,
              child: GeneratedTEANSACTIONWidget1(),
            ),
            Positioned(
              left: 325.0,
              top: 124.0,
              right: null,
              bottom: null,
              width: 36.0,
              height: 36.0,
              child: GeneratedREFRESHWidget2(),
            ),
            Positioned(
              left: 14.0,
              top: 124.0,
              right: null,
              bottom: null,
              width: 305.0,
              height: 36.0,
              child: GeneratedACTUSWidget2(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 74.0,
              child: GeneratedHEADERSWidget1(),
            ),
            Positioned(
              left: 14.0,
              top: 738.0,
              right: null,
              bottom: null,
              width: 346.0,
              height: 44.0,
              child: GeneratedTOOLBARWidget3(),
            ),
            Positioned(
              left: 4.0,
              top: 165.0,
              right: null,
              bottom: null,
              width: 367.0,
              height: 292.0,
              child: GeneratedCARDVENDEURWidget2(),
            ),
            Positioned(
              left: 0.0,
              top: 74.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 44.0,
              child: GeneratedHEADBARWidget2(),
            )
          ]),
    ));
  }
}
