import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/svg/svg.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Line                                            VENDEUR
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVENDEURWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: TransformHelper.rotate(
            a: 1.00,
            b: 0.00,
            c: -0.00,
            d: 1.00,
            child: Container(
              width: 3337.025390625,
              height: 0.0,
              child: SvgWidget(painters: [
                SvgPathPainter.stroke(
                  0.0,
                  strokeCap: StrokeCap.round,
                  strokeJoin: StrokeJoin.miter,
                )..color = Color.fromARGB(255, 255, 123, 142),
              ]),
            )));
  }
}
