import 'package:flutter/material.dart';
import 'package:flutterapp/sutch_clientapp/generatedclientconnexionwidget/generated/GeneratedTOOLBARWidget17.dart';
import 'package:flutterapp/sutch_clientapp/generatedclientconnexionwidget/generated/GeneratedBOXBOXWidget9.dart';
import 'package:flutterapp/sutch_clientapp/generatedclientconnexionwidget/generated/GeneratedBackgroundWidget28.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/sutch_clientapp/generatedclientconnexionwidget/generated/GeneratedBOXBOXWidget8.dart';
import 'package:flutterapp/sutch_clientapp/generatedclientconnexionwidget/generated/GeneratedHeaderWidget14.dart';

/* Frame                                CLIENT Connexion
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCLIENTConnexionWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 375.0,
              height: 812.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 244, 244, 244),
                      ),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width =
                            constraints.maxWidth * 1.0906666666666667;

                        final double height =
                            constraints.maxHeight * 1.1625615763546797;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: constraints.maxWidth * -0.04,
                              y: constraints.maxHeight * -0.0960591133004926,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child: GeneratedBackgroundWidget28(),
                              ))
                        ]);
                      }),
                    )
                  ]),
            ),
            Positioned(
              left: 375.0,
              top: 288.0,
              right: null,
              bottom: null,
              width: 297.0,
              height: 312.0,
              child: GeneratedBOXBOXWidget8(),
            ),
            Positioned(
              left: 4.0,
              top: 822.0,
              right: null,
              bottom: null,
              width: 367.0,
              height: 44.0,
              child: GeneratedTOOLBARWidget17(),
            ),
            Positioned(
              left: 39.0,
              top: 288.0,
              right: null,
              bottom: null,
              width: 297.0,
              height: 312.0,
              child: GeneratedBOXBOXWidget9(),
            ),
            Positioned(
              left: -155.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 561.0,
              height: 155.0,
              child: GeneratedHeaderWidget14(),
            )
          ]),
    ));
  }
}
