import 'package:flutter/material.dart';

/* Text VOUS PARTEZ DEJA ?
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVOUSPARTEZDEJAWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Align(
      alignment: Alignment.center,
      child: Text(
        '''VOUS PARTEZ DEJA ?''',
        overflow: TextOverflow.visible,
        textAlign: TextAlign.center,
        style: TextStyle(
          height: 1.4849999745686848,
          fontSize: 12.0,
          fontFamily: 'Roboto',
          fontWeight: FontWeight.w500,
          color: Color.fromARGB(255, 106, 106, 106),

          /* letterSpacing: 2.4000000000000004, */
        ),
      ),
    ));
  }
}
