import 'package:flutter/material.dart';
import 'package:flutterapp/sutch_clientapp/generatedgroup2widget/generated/GeneratedRECOUIWidget.dart';
import 'package:flutterapp/sutch_clientapp/generatedgroup2widget/generated/GeneratedOUIWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Instance Group 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 75.0,
      height: 26.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth;

                final double height = constraints.maxHeight;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: 0,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedRECOUIWidget(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.4;

                final double height =
                    constraints.maxHeight * 0.8846153846153846;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.3333333333333333,
                      y: constraints.maxHeight * 0.15384615384615385,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedOUIWidget(),
                      ))
                ]);
              }),
            )
          ]),
    ));
  }
}
