import 'package:flutter/material.dart';
import 'package:flutterapp/sutch_clientapp/generatedaccueilwidget/generated/GeneratedHEADBARWidget12.dart';
import 'package:flutterapp/sutch_clientapp/generatedaccueilwidget/generated/GeneratedSTATWidget1.dart';
import 'package:flutterapp/sutch_clientapp/generatedaccueilwidget/generated/GeneratedHEADERSWidget11.dart';
import 'package:flutterapp/sutch_clientapp/generatedaccueilwidget/generated/GeneratedREFRESHWidget12.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/sutch_clientapp/generatedaccueilwidget/generated/GeneratedMONEYWidget1.dart';
import 'package:flutterapp/sutch_clientapp/generatedaccueilwidget/generated/GeneratedACTUSWidget12.dart';
import 'package:flutterapp/sutch_clientapp/generatedaccueilwidget/generated/GeneratedTOPWidget1.dart';
import 'package:flutterapp/sutch_clientapp/generatedaccueilwidget/generated/GeneratedENCHEREWidget4.dart';
import 'package:flutterapp/sutch_clientapp/generatedaccueilwidget/generated/GeneratedBackgroundWidget15.dart';
import 'package:flutterapp/sutch_clientapp/generatedaccueilwidget/generated/GeneratedTOOLBARWidget13.dart';

/* Frame Accueil
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAccueilWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
          Container(
            width: 375.0,
            height: 812.0,
            child: Stack(
                fit: StackFit.expand,
                alignment: Alignment.center,
                overflow: Overflow.visible,
                children: [
                  ClipRRect(
                    borderRadius: BorderRadius.zero,
                    child: Container(
                      color: Color.fromARGB(255, 244, 244, 244),
                    ),
                  ),
                  Positioned(
                    left: 0.0,
                    top: 0.0,
                    right: 0.0,
                    bottom: 0.0,
                    width: null,
                    height: null,
                    child: LayoutBuilder(builder:
                        (BuildContext context, BoxConstraints constraints) {
                      final double width = constraints.maxWidth * 1.08;

                      final double height =
                          constraints.maxHeight * 0.07881773399014778;

                      return Stack(children: [
                        TransformHelper.translate(
                            x: constraints.maxWidth * -0.04,
                            y: constraints.maxHeight * -0.09113300492610837,
                            z: 0,
                            child: Container(
                              width: width,
                              height: height,
                              child: GeneratedBackgroundWidget15(),
                            ))
                      ]);
                    }),
                  )
                ]),
          ),
          Positioned(
            left: 190.0,
            top: 495.0,
            right: null,
            bottom: null,
            width: 175.0,
            height: 233.0,
            child: GeneratedENCHEREWidget4(),
          ),
          Positioned(
            left: 14.0,
            top: 498.0,
            right: null,
            bottom: null,
            width: 165.0,
            height: 227.0,
            child: GeneratedTOPWidget1(),
          ),
          Positioned(
            left: 14.0,
            top: 396.0,
            right: null,
            bottom: null,
            width: 345.0,
            height: 90.0,
            child: GeneratedMONEYWidget1(),
          ),
          Positioned(
            left: 325.0,
            top: 124.0,
            right: null,
            bottom: null,
            width: 36.0,
            height: 36.0,
            child: GeneratedREFRESHWidget12(),
          ),
          Positioned(
            left: 14.0,
            top: 124.0,
            right: null,
            bottom: null,
            width: 305.0,
            height: 36.0,
            child: GeneratedACTUSWidget12(),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 74.0,
            child: GeneratedHEADERSWidget11(),
          ),
          Positioned(
            left: 14.0,
            top: 166.0,
            right: null,
            bottom: null,
            width: 345.0,
            height: 219.0,
            child: GeneratedSTATWidget1(),
          ),
          Positioned(
            left: 14.0,
            top: 738.0,
            right: null,
            bottom: null,
            width: 346.0,
            height: 44.0,
            child: GeneratedTOOLBARWidget13(),
          ),
          Positioned(
            left: 0.0,
            top: 75.0,
            right: null,
            bottom: null,
            width: 374.0,
            height: 42.0,
            child: GeneratedHEADBARWidget12(),
          )
        ]));
  }
}
