import 'package:flutter/material.dart';
import 'package:flutterapp/sutch_clientapp/generatedcardvdextdwidget/generated/GeneratedCARDVDADHWidget1.dart';

/* Frame CARD VD EXTD
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCARDVDEXTDWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 388.0,
      height: 425.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 385.0,
              height: 487.0,
              child: GeneratedCARDVDADHWidget1(),
            )
          ]),
    ));
  }
}
