import 'package:flutter/material.dart';
import 'package:flutterapp/sutch_clientapp/generatedvendeuraddcatclavierwidget1/generated/GeneratedHEADERSWidget7.dart';
import 'package:flutterapp/sutch_clientapp/generatedvendeuraddcatclavierwidget1/generated/GeneratedCARDVENDEURWidget11.dart';
import 'package:flutterapp/sutch_clientapp/generatedvendeuraddcatclavierwidget1/generated/GeneratedClavierWidget4.dart';
import 'package:flutterapp/sutch_clientapp/generatedvendeuraddcatclavierwidget1/generated/GeneratedHEADBARWidget8.dart';
import 'package:flutterapp/sutch_clientapp/generatedvendeuraddcatclavierwidget1/generated/GeneratedACTUSWidget8.dart';
import 'package:flutterapp/sutch_clientapp/generatedvendeuraddcatclavierwidget1/generated/GeneratedREFRESHWidget8.dart';
import 'package:flutterapp/sutch_clientapp/generatedvendeuraddcatclavierwidget1/generated/GeneratedBackgroundWidget11.dart';
import 'package:flutterapp/sutch_clientapp/generatedvendeuraddcatclavierwidget1/generated/GeneratedMAPWidget8.dart';
import 'package:flutterapp/sutch_clientapp/generatedvendeuraddcatclavierwidget1/generated/GeneratedTOOLBARWidget9.dart';
import 'package:flutterapp/sutch_clientapp/generatedvendeuraddcatclavierwidget1/generated/GeneratedCARTEVENDEURWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Frame Vendeur / ADD CAT / Clavier
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVendeurADDCATClavierWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 375.0,
              height: 812.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 244, 244, 244),
                      ),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 190.0,
                      right: null,
                      bottom: null,
                      width: 375.0,
                      height: 274.0,
                      child: GeneratedCARDVENDEURWidget11(),
                    ),
                    Positioned(
                      left: 14.0,
                      top: 165.0,
                      right: null,
                      bottom: null,
                      width: 348.0,
                      height: 28.0,
                      child: GeneratedCARTEVENDEURWidget(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width = constraints.maxWidth * 1.08;

                        final double height =
                            constraints.maxHeight * 0.07881773399014778;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: constraints.maxWidth * -0.04,
                              y: constraints.maxHeight * -0.09113300492610837,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child: GeneratedBackgroundWidget11(),
                              ))
                        ]);
                      }),
                    )
                  ]),
            ),
            Positioned(
              left: 9.0,
              top: 467.0,
              right: null,
              bottom: null,
              width: 358.0,
              height: 266.0,
              child: GeneratedMAPWidget8(),
            ),
            Positioned(
              left: 325.0,
              top: 124.0,
              right: null,
              bottom: null,
              width: 36.0,
              height: 36.0,
              child: GeneratedREFRESHWidget8(),
            ),
            Positioned(
              left: 14.0,
              top: 124.0,
              right: null,
              bottom: null,
              width: 305.0,
              height: 36.0,
              child: GeneratedACTUSWidget8(),
            ),
            Positioned(
              left: 0.0,
              top: 74.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 44.0,
              child: GeneratedHEADBARWidget8(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 74.0,
              child: GeneratedHEADERSWidget7(),
            ),
            Positioned(
              left: -4.0,
              top: 477.0,
              right: null,
              bottom: null,
              width: 382.0,
              height: 44.0,
              child: GeneratedTOOLBARWidget9(),
            ),
            Positioned(
              left: 0.0,
              top: 520.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 293.0,
              child: GeneratedClavierWidget4(),
            )
          ]),
    ));
  }
}
