import 'package:flutter/material.dart';
import 'package:flutterapp/sutch_clientapp/generatedvendeuraddcatclavierwidget/generated/GeneratedCARTEVENDEURENATTENTEWidget.dart';
import 'package:flutterapp/sutch_clientapp/generatedvendeuraddcatclavierwidget/generated/GeneratedClavierWidget3.dart';
import 'package:flutterapp/sutch_clientapp/generatedvendeuraddcatclavierwidget/generated/GeneratedACTUSWidget5.dart';
import 'package:flutterapp/sutch_clientapp/generatedvendeuraddcatclavierwidget/generated/GeneratedHEADBARWidget5.dart';
import 'package:flutterapp/sutch_clientapp/generatedvendeuraddcatclavierwidget/generated/GeneratedHEADERSWidget4.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/sutch_clientapp/generatedvendeuraddcatclavierwidget/generated/GeneratedTOOLBARWidget6.dart';
import 'package:flutterapp/sutch_clientapp/generatedvendeuraddcatclavierwidget/generated/GeneratedCARDVENDEURWidget8.dart';
import 'package:flutterapp/sutch_clientapp/generatedvendeuraddcatclavierwidget/generated/GeneratedMAPWidget2.dart';
import 'package:flutterapp/sutch_clientapp/generatedvendeuraddcatclavierwidget/generated/GeneratedREFRESHWidget5.dart';
import 'package:flutterapp/sutch_clientapp/generatedvendeuraddcatclavierwidget/generated/GeneratedBackgroundWidget8.dart';

/* Frame Vendeur / ADD CAT / Clavier
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVendeurADDCATClavierWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
          Container(
            width: 375.0,
            height: 812.0,
            child: Stack(
                fit: StackFit.expand,
                alignment: Alignment.center,
                overflow: Overflow.visible,
                children: [
                  ClipRRect(
                    borderRadius: BorderRadius.zero,
                    child: Container(
                      color: Color.fromARGB(255, 244, 244, 244),
                    ),
                  ),
                  Positioned(
                    left: 14.0,
                    top: 165.0,
                    right: null,
                    bottom: null,
                    width: 348.0,
                    height: 28.0,
                    child: GeneratedCARTEVENDEURENATTENTEWidget(),
                  ),
                  Positioned(
                    left: 0.0,
                    top: 0.0,
                    right: 0.0,
                    bottom: 0.0,
                    width: null,
                    height: null,
                    child: LayoutBuilder(builder:
                        (BuildContext context, BoxConstraints constraints) {
                      final double width = constraints.maxWidth * 1.08;

                      final double height =
                          constraints.maxHeight * 0.07881773399014778;

                      return Stack(children: [
                        TransformHelper.translate(
                            x: constraints.maxWidth * -0.04,
                            y: constraints.maxHeight * -0.09113300492610837,
                            z: 0,
                            child: Container(
                              width: width,
                              height: height,
                              child: GeneratedBackgroundWidget8(),
                            ))
                      ]);
                    }),
                  )
                ]),
          ),
          Positioned(
            left: 9.0,
            top: 467.0,
            right: null,
            bottom: null,
            width: 358.0,
            height: 266.0,
            child: GeneratedMAPWidget2(),
          ),
          Positioned(
            left: 4.0,
            top: 192.0,
            right: null,
            bottom: null,
            width: 367.0,
            height: 265.0,
            child: GeneratedCARDVENDEURWidget8(),
          ),
          Positioned(
            left: 325.0,
            top: 124.0,
            right: null,
            bottom: null,
            width: 36.0,
            height: 36.0,
            child: GeneratedREFRESHWidget5(),
          ),
          Positioned(
            left: 14.0,
            top: 124.0,
            right: null,
            bottom: null,
            width: 305.0,
            height: 36.0,
            child: GeneratedACTUSWidget5(),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 74.0,
            child: GeneratedHEADERSWidget4(),
          ),
          Positioned(
            left: -4.0,
            top: 477.0,
            right: null,
            bottom: null,
            width: 382.0,
            height: 44.0,
            child: GeneratedTOOLBARWidget6(),
          ),
          Positioned(
            left: 0.0,
            top: 74.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 44.0,
            child: GeneratedHEADBARWidget5(),
          ),
          Positioned(
            left: 0.0,
            top: 520.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 293.0,
            child: GeneratedClavierWidget3(),
          )
        ]));
  }
}
