import 'package:flutter/material.dart';

/* Rectangle - - - - - CLIENT SECTION - - - - - -
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCLIENTSECTIONWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 24.0,
      height: 1436.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(50.0),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(50.0),
        child: Container(
          color: Color.fromARGB(255, 151, 199, 226),
        ),
      ),
    ));
  }
}
