import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/sutch_clientapp/generatedbtincatwidget1/generated/GeneratedRectangle12Widget30.dart';
import 'package:flutterapp/sutch_clientapp/generatedbtincatwidget1/generated/GeneratedRobeWidget5.dart';

/* Instance BT IN CAT
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBTINCATWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 70.0,
      height: 23.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth;

                final double height = constraints.maxHeight;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: 0,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedRectangle12Widget30(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth * 0.9308035714285714;

                final double height =
                    constraints.maxHeight * 1.0434782608695652;

                return Stack(children: [
                  TransformHelper.translate(
                      x: constraints.maxWidth * 0.09375,
                      y: constraints.maxHeight * 0.08695652173913043,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedRobeWidget5(),
                      ))
                ]);
              }),
            )
          ]),
    ));
  }
}
