import 'package:flutter/material.dart';
import 'package:flutterapp/sutch_clientapp/generatedslidebarwidget/generated/GeneratedFONCTIONSlideBARWidget1.dart';

/* Frame Slide Bar
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSlideBarWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Opacity(
      opacity: 0.9800000190734863,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 201.0,
              height: 812.0,
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 201.0,
              height: 812.0,
              child: GeneratedFONCTIONSlideBARWidget1(),
            )
          ]),
    ));
  }
}
